spring.application.name=bd
spring.datasource.url=jdbc:postgresql://localhost:5432/produtospp1es
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

